import type { Product } from "./types";

// Seed catalogue. Used directly in demo mode, and as the one-click
// seed for Firestore when you click "Seed sample products" in /admin.
export const SEED_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Golden Heart Ring",
    category: "rings",
    collection: "gold",
    price: 899,
    description: "A sculpted golden heart ring that makes a statement of bold love.",
    variants: ["6", "7", "8"],
    icon: "💍",
    image: "/products/1.jpg",
  },
  {
    id: "prod-2",
    name: "Textured Shell Ring",
    category: "rings",
    collection: "gold",
    price: 949,
    description: "A solid gold ring featuring a deeply textured seashell design.",
    variants: ["6", "7", "8"],
    icon: "💍",
    image: "/products/2.jpg",
  },
  {
    id: "prod-3",
    name: "Oversized Shell Earring",
    category: "earrings",
    collection: "gold",
    price: 1299,
    description: "A bold, oversized golden shell stud earring inspired by the ocean.",
    variants: [],
    icon: "🐚",
    image: "/products/3.jpg",
  },
  {
    id: "prod-4",
    name: "Golden Pendant Neckpieces",
    category: "neckpieces",
    collection: "gold",
    price: 1499,
    description: "A set of delicate golden neckpieces featuring distinct, elegant pendants.",
    variants: ["Black Square", "White Square", "Shell"],
    icon: "📿",
    image: "/products/4.jpg",
  },
  {
    id: "prod-5",
    name: "Double Pearl Droplet Ring",
    category: "rings",
    collection: "pastel",
    price: 799,
    description: "An elegant twin-droplet ring featuring two smooth white pearls.",
    variants: ["6", "7", "8"],
    icon: "💍",
    image: "/products/5.jpg",
  },
  {
    id: "prod-6",
    name: "Spiral Vine Arm Cuff",
    category: "armcuffs",
    collection: "gold",
    price: 1699,
    description: "A mesmerizing spiral arm cuff adorned with golden leaf accents.",
    variants: ["Adjustable"],
    icon: "✨",
    image: "/products/6.jpg",
  },
  {
    id: "prod-7",
    name: "Golden Bow Ring",
    category: "rings",
    collection: "gold",
    price: 849,
    description: "A charming, smoothly sculpted golden bow ring.",
    variants: ["6", "7", "8"],
    icon: "💍",
    image: "/products/7.jpg",
  },
  {
    id: "prod-8",
    name: "Pearl Blossom Ring",
    category: "rings",
    collection: "pastel",
    price: 999,
    description: "A stunning floral ring featuring delicate pearl-like petals and a golden center.",
    variants: ["6", "7", "8"],
    icon: "🌸",
    image: "/products/8.jpg",
  },
  {
    id: "prod-9",
    name: "Pink Hibiscus Ring",
    category: "rings",
    collection: "pastel",
    price: 1049,
    description: "A vibrant, beautifully crafted pink enamel hibiscus flower ring.",
    variants: ["6", "7", "8"],
    icon: "🌺",
    image: "/products/9.jpg",
  },
  {
    id: "prod-10",
    name: "Geometric Hex Hoop",
    category: "earrings",
    collection: "gold",
    price: 1199,
    description: "A striking, sculptural hexagonal golden hoop earring.",
    variants: [],
    icon: "✨",
    image: "/products/10.jpg",
  },
  {
    id: "prod-11",
    name: "Starfish Wrap Ring",
    category: "rings",
    collection: "gold",
    price: 899,
    description: "A whimsical golden ring featuring twin starfish wrapped around your finger.",
    variants: ["Adjustable"],
    icon: "⭐",
    image: "/products/11.jpg",
  },
  {
    id: "prod-12",
    name: "Golden Bean Ring",
    category: "rings",
    collection: "gold",
    price: 749,
    description: "A smooth, contemporary golden bean ring with an adjustable band.",
    variants: ["Adjustable"],
    icon: "💍",
    image: "/products/12.jpg",
  },
  {
    id: "prod-13",
    name: "Organic Pearl Stone Ring",
    category: "rings",
    collection: "pastel",
    price: 999,
    description: "A gorgeous, raw-cut white stone set within an organic golden bezel.",
    variants: ["6", "7", "8"],
    icon: "💍",
    image: "/products/13.jpg",
  },
  {
    id: "prod-14",
    name: "Liquid Gold Teardrop Earring",
    category: "earrings",
    collection: "gold",
    price: 1299,
    description: "A heavy, luxurious teardrop earring that looks like melting gold.",
    variants: [],
    icon: "✨",
    image: "/products/14.jpg",
  },
  {
    id: "prod-15",
    name: "White Coral Branch Ring",
    category: "rings",
    collection: "pastel",
    price: 1149,
    description: "An intricate branch-like ring adorned with multiple white coral-like stones.",
    variants: ["6", "7", "8"],
    icon: "💍",
    image: "/products/15.jpg",
  }
];
